"""Added a column

Revision ID: 41452ef58e48
Revises: 
Create Date: 2017-10-31 11:00:08.509396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41452ef58e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('innovation', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('science', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('technology', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'technology')
    op.drop_column('users', 'science')
    op.drop_column('users', 'innovation')
    # ### end Alembic commands ###
